export const strings = {
  lang: "en",
  dir: "ltr",
  vowels: ['a', 'e', 'i', 'o', 'u'],
  consonants: [
    'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n',
    'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'
  ],
  appName: "W.O.R.D",
  subtitle: "Multiplayer English Word Construction",
  startGame: "Start Game",
  restartGame: "Start New Round",
  loadingGame: "⌛ Creating game...",
  rulesTitle: "How to Play",
  rule1: "1. 5 English letters are assigned to all players.",
  rule2: "2. Form valid English words with at least 3 letters using given letters.",
  rule3: "3. Reusing given letters in a word is allowed.",
  rule4: "4. Points are awarded based on word length.",
  rule5: "5. Player who reaching 50% of total points wins the game!",
  rule5: "6. The game ends if all words are found or no player finds a new word for 3 minutes.",

  possibleWordsTitle: "List of possible words ({n} words):",
  hostLabel: "Host",
  youLabel: "(You)",
  lettersTitle: "Round Letters:",
  yourInputPlaceholder: "Type or tap letters...",
  submitWord: "Submit",
  clearInput: "Clear",
  backspace: "Del",

  scoreboardTitle: "Scoreboard",
  foundWordsTitle: "Discovered Words",
  noWordsYet: "No words found yet. Be the first to build a word!",
  totalPossibleWords: "Total possible words:",
  totalPossiblePoints: "Total possible points:",
  progress: "Round progress:",

  statusActive: "Game in progress...",
  statusEnded: "Game ended",
  statusWaiting: "Waiting for start...",
  statusStartingIn: "⏳ Starting in {s}s",
  statusWaitingPlayer: "⏳ Waiting for player 2...",

  waitingLobbyTitle: "Waiting for second player...",
  waitingLobbyDesc: "Game created and will bet starts as soon as the second player joins",
  waitingLobbyCountdownTitle: "Second player joined!",
  waitingLobbyCountdownDesc: "For fairness, a short countdown has started.",
  secondsToStart: "seconds until start...",

  historyBtn: "📜 View Game History",
  historyTitle: "📜 Game History",
  closeBtn: "Close ✕",
  noHistoryYet: "No recorded games in history yet.",
  roundNumber: "Round #{n}",
  foundWordsCount: "Discovered Words ({n} words):",
  noWordsInRound: "No words were discovered in this round.",
  participantsLabel: "Participants:",
  scorePts: "{score} pts",

  timeRemaining: "Time remaining:",
  lastWordFound: "Last word found:",
  minutesAgo: "m ago",
  secondsAgo: "s ago",
  justNow: "just now",

  resignBtn: "Resign",
  resignedMsg: "resigned",
  resignedLabel: "Resigned",
  resignedFeedback: "You have resigned from this round.",
  claimHostBtn: "Claim Host (Host inactive)",

  errTooShort: "Word must be at least 3 letters long!",
  errInvalidLetters: "Word uses letters outside the given 5 letters!",
  errNotInDict: "Word not found in the dictionary!",
  errAlreadyFound: "Word has already been claimed by a player!",
  errGameEnded: "Game has ended!",
  errYouHaveResigned: "You have resigned from this round!",
  errResignLock: "Resignation is locked for the first 2 minutes of the game.",
  errInvalidChar: "⚠️ Letter '{char}' is not in this round's letters!",

  successWord: "Great! +{pts} points for '{word}'",

  winnerTitle: "🎉 Game Over - Winner:",
  noWinner: "Game ended without a winner.",
  gameOverReasonWords: "All possible words were found!",
  gameOverReasonHalfPoints: "A player reached 50% of total points!",
  gameOverReasonResign: "All other players resigned!",
  gameOverReasonTimeout: "No new words found for 3 minutes!",

  simulatedPlayers: "Multiplayer Simulator (Dev Mode):",
  switchPlayer: "Switch Active Player:",
  exportXdcBtn: "Download .xdc Package",
  resetSimBtn: "Reset Simulator",
  resetSimConfirm: "Clear simulator data for all players?",

  // UI icons / separators used by the scripts
  backspaceIcon: "⌦",
  lobbyWaitingIcon: "⏳",
  lobbyCountdownIcon: "🎉",
  roundIcon: "🎮",
  winnerIcon: "🏆",
  foundWordMark: "✓ ",
  participantsBullet: "• ",
  lettersSeparator: " ، ",
  listSeparator: "، ",
  letterAriaLabel: "Letter {letter}",
  themeToggle: "Toggle light/dark theme",
  timeLocale: "en-US",
  progressStats: "{found} / {totalWords} ({foundPts} / {totalPts} pts)",
  fallbackPlayerName: "a player",

  // Chat update messages (webxdc info/summary)
  msgStartRound: "🎮 {name} started a new game!",
  msgPlayerJoined: "👤 {name} joined the game.",
  msgGameEndedWinner: "🎉 Game over! Winner: {winner}",
  msgGameEnded: "🏁 Game over ({reason})",
  msgRoundSummary: "Round letters: {letters}",
  msgConcurrentGame: "Another game was started at the same time by another user. You were moved to the first game."
};
